# 更多工作流配置参考：https://github.com/actions/starter-workflows
# CI工作流名字
name: 'CI'

on:
  # 控制CI当main分支有push动作触发的时候执行工作流
  push:
    branches: ['none']

jobs:
  # 工作流中的一个叫做build的任务job
  build:
    name: Build Project & Upload Artifact
    # build这项任务会在ubuntu上进行执行
    runs-on: macos-latest

    # 执行build这项任务的具体步骤是
    steps:
      # step1：使用actions/checkout@v3这个包拉这个项目的代码
      - uses: actions/checkout@v3

      # step2：在
      - name: Setup Node
        uses: actions/setup-node@v3
        with: # 指定相关信息
          node-version: '14' # 执行node版本是14

      # step3：请使用pnpm/action-setup@v2下载pnpm
      - name: Install Pnpm # 给step2取个名字吧
        uses: pnpm/action-setup@v2 # 一样的，在pnpm这个用户|组织下，有个action-setup的仓库，它的v2分支已经帮我们写好了相关下载pnpm的代码

      # step4: 构建软件
      - name: Build Project
        run:  pnpm run build

      # step5: 上传软件
      - name: Upload Project
        uses: actions/upload-artifact@v3.1.2

  # release: